import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h3>About Page</h3>
          <Link href='/'>Back to the Top Page</Link>
        </div>
      </main>
    </>
  )
}
