import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home(props:any) {
  const fnc=props.all.countUpFnc;
  console.log(fnc)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h3>Top Page</h3>
          <Link href='/components/about'>Goto About</Link>
          <br />
          <button onClick={fnc}>増加</button>
        </div>
        
        {/* レスポンシブデザイン */}
        <div className={styles.respo_div}>
          <h3 className={styles.respo_h3}>ここにレスポンシブのテキストボックスを作ります。</h3>
          <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor id sapiente, quos, minima voluptatibus sed enim fugiat at distinctio, iste porro pariatur. In qui eius sit doloremque? Aliquam expedita quidem odio quia eaque repudiandae velit iure quam. Perferendis, quo quos est nam nulla blanditiis provident consequatur necessitatibus molestias eligendi expedita quidem architecto recusandae explicabo beatae. Dolores eveniet vel eius molestiae tenetur ullam vero neque saepe at obcaecati necessitatibus animi sed dicta totam, maiores perspiciatis quia eos rerum voluptatem enim placeat blanditiis eum voluptates consequuntur! Voluptas accusamus aperiam nostrum minus officia, aliquam recusandae natus nemo iusto ducimus accusantium omnis expedita! Nulla?
          </p>
        </div>
        
      </main>
    </>
  )
}
